/* autogenerated by Processing revision 1286 on 2025-10-31 */
import processing.core.*;
import processing.data.*;
import processing.event.*;
import processing.opengl.*;

import java.util.HashMap;
import java.util.ArrayList;
import java.io.File;
import java.io.BufferedReader;
import java.io.PrintWriter;
import java.io.InputStream;
import java.io.OutputStream;
import java.io.IOException;

public class Calculator2 extends PApplet {

// Jamie Duersch | Oct 10 | Calculator

Button[] buttons = new Button[13];
Button[] numButtons = new Button[10];
float l, r, result;
String dVal;
String op;
boolean left;

 public void setup() {
  /* size commented out by preprocessor */;
  background(0);
  l = 0.0f;
  r = 0.0f;
  result = 0.0f;
  dVal = "0";
  op = "";
  left = true;

  // Function Buttons
  buttons[0] = new Button(25, 65, 30, 30, "+/-", 0xFFFFFFFF, 0xFFAAAAAA);
  buttons[1] = new Button(65, 65, 30, 30, "rnd", 0xFFFFFFFF, 0xFFAAAAAA);
  buttons[2] = new Button(105, 65, 30, 30, "^", 0xFFFFFFFF, 0xFFAAAAAA);
  buttons[3] = new Button(25, 105, 30, 30, "√", 0xFFFFFFFF, 0xFFAAAAAA);
  buttons[4] = new Button(65, 105, 30, 30, "π", 0xFFFFFFFF, 0xFFAAAAAA);
  buttons[5] = new Button(105, 105, 30, 30, "del", 0xFFFFFFFF, 0xFFAAAAAA);
  buttons[6] = new Button(170, 105, 30, 30, "*", 0xFFFFFFFF, 0xFFAAAAAA);
  buttons[7] = new Button(170, 65, 30, 30, "/", 0xFFFFFFFF, 0xFFAAAAAA);
  buttons[8] = new Button(170, 145, 30, 30, "-", 0xFFFFFFFF, 0xFFAAAAAA);
  buttons[9] = new Button(170, 185, 30, 30, "+", 0xFFFFFFFF, 0xFFAAAAAA);
  buttons[10] = new Button(105, 265, 30, 30, ".", 0xFFFFFFFF, 0xFFAAAAAA);
  buttons[11] = new Button(170, 245, 30, 70, "=", 0xFFFFFFFF, 0xFFAAAAAA);
  buttons[12] = new Button(25, 265, 30, 30, "C", 0xFFFFFFFF, 0xFFAAAAAA);

  // Number Buttons
  numButtons[9] = new Button(105, 145, 30, 30, "9", 0xFFFFFFFF, 0xFFAAAAAA);
  numButtons[8] = new Button(65, 145, 30, 30, "8", 0xFFFFFFFF, 0xFFAAAAAA);
  numButtons[7] = new Button(25, 145, 30, 30, "7", 0xFFFFFFFF, 0xFFAAAAAA);
  numButtons[6] = new Button(105, 185, 30, 30, "6", 0xFFFFFFFF, 0xFFAAAAAA);
  numButtons[5] = new Button(65, 185, 30, 30, "5", 0xFFFFFFFF, 0xFFAAAAAA);
  numButtons[4] = new Button(25, 185, 30, 30, "4", 0xFFFFFFFF, 0xFFAAAAAA);
  numButtons[3] = new Button(105, 225, 30, 30, "3", 0xFFFFFFFF, 0xFFAAAAAA);
  numButtons[2] = new Button(65, 225, 30, 30, "2", 0xFFFFFFFF, 0xFFAAAAAA);
  numButtons[1] = new Button(25, 225, 30, 30, "1", 0xFFFFFFFF, 0xFFAAAAAA);
  numButtons[0] = new Button(65, 265, 30, 30, "0", 0xFFFFFFFF, 0xFFAAAAAA);
}

 public void draw() {
  background(50);
  for (int i = 0; i < buttons.length; i++) {
    buttons[i].display();
    buttons[i].hover(mouseX, mouseY);
  }
  for (int i = 0; i < numButtons.length; i++) {
    numButtons[i].display();
    numButtons[i].hover(mouseX, mouseY);
  }
  updateDisplay();
}

 public void keyPressed() {
  println("Key:" + key);
  println("Key Code:" + keyCode);
  // ===== CLEAR =====
  if (key == 'c' || key == 'C') {
    l = r = result = 0;
    dVal = "0";
    op = "";
    left = true;
  }

  // ===== DELETE / BACKSPACE =====
  else if (keyCode == BACKSPACE || key == 'd' || key == 'D') {
    if (dVal.length() > 1) dVal = dVal.substring(0, dVal.length() - 1);
    else dVal = "0";
    if (left) l = PApplet.parseFloat(dVal);
    else r = PApplet.parseFloat(dVal);
  }

  // ===== OPERATORS =====
  else if (key == '+') {
    op = "+";
    left = false;
    dVal = "0";
  } 
  else if (key == '-') {
    op = "-";
    left = false;
    dVal = "0";
  } 
  else if (key == '*') {
    op = "*";
    left = false;
    dVal = "0";
  } 
  else if (key == '/') {
    op = "/";
    left = false;
    dVal = "0";
  } 
  else if (key == '^') {
    op = "^";
    left = false;
    dVal = "0";
  }

  // ===== EQUAL / ENTER =====
  else if (key == '=' || keyCode == ENTER || keyCode == RETURN) {
    performCalculation();
    l = result;
    left = true;
  }

  // ===== DECIMAL POINT =====
  else if (key == '.') {
    if (!dVal.contains(".")) dVal += ".";
  }

  // ===== PI (π) =====
  else if (key == 'p' || key == 'P') {
    if (left) l = PI;
    else r = PI;
    dVal = str(PI);
  }

  // ===== ROUND (rnd) =====
  else if (key == 'r' || key == 'R') {
    float temp = round(PApplet.parseFloat(dVal));
    dVal = str(temp);
    if (left) l = temp;
    else r = temp;
  }

  // ===== NEGATE (+/-) =====
  else if (key == 'n' || key == 'N') {
    float temp = PApplet.parseFloat(dVal) * -1;
    dVal = str(temp);
    if (left) l = temp;
    else r = temp;
  }

  // ===== SQUARE ROOT (√) =====
  else if (key == 's' || key == 'S' || key == 'v' || key == '√') {
    float temp = sqrt(PApplet.parseFloat(dVal));
    dVal = str(temp);
    if (left) l = temp;
    else r = temp;
  }

  else if (keyCode == 48 || keyCode == 96) {
    if (dVal.length()<17) {
        if (left == true) {
            if (dVal.equals("0")) {
                dVal = "0";
                l = PApplet.parseFloat(dVal);
            } else {
                dVal += "0";
                l = PApplet.parseFloat(dVal);
            }
        } else if (!left)
          if (dVal.equals("0")) {
            dVal = "0";
            r = PApplet.parseFloat(dVal);
          } else {
            dVal += "0";
            r = PApplet.parseFloat(dVal);
          }
      }
  }
  else if (keyCode == 49 || keyCode == 97) {
    if (dVal.length()<17) {
        if (left == true) {
            if (dVal.equals("0")) {
                dVal = "1";
                l = PApplet.parseFloat(dVal);
            } else {
                dVal += "1";
                l = PApplet.parseFloat(dVal);
            }
        } else if (!left)
          if (dVal.equals("0")) {
            dVal = "1";
            r = PApplet.parseFloat(dVal);
          } else {
            dVal += "1";
            r = PApplet.parseFloat(dVal);
          }
      }
  }
  else if (keyCode == 50 || keyCode == 98) {
    if (dVal.length()<17) {
        if (left == true) {
            if (dVal.equals("0")) {
                dVal = "2";
                l = PApplet.parseFloat(dVal);
            } else {
                dVal += "2";
                l = PApplet.parseFloat(dVal);
            }
        } else if (!left)
          if (dVal.equals("0")) {
            dVal = "2";
            r = PApplet.parseFloat(dVal);
          } else {
            dVal += "2";
            r = PApplet.parseFloat(dVal);
          }
      }
  }
  else if (keyCode == 51 || keyCode == 99) {
    if (dVal.length()<17) {
        if (left == true) {
            if (dVal.equals("0")) {
                dVal = "3";
                l = PApplet.parseFloat(dVal);
            } else {
                dVal += "3";
                l = PApplet.parseFloat(dVal);
            }
        } else if (!left)
          if (dVal.equals("0")) {
            dVal = "3";
            r = PApplet.parseFloat(dVal);
          } else {
            dVal += "3";
            r = PApplet.parseFloat(dVal);
          }
      }
  }
  else if (keyCode == 52 || keyCode == 100) {
    if (dVal.length()<17) {
        if (left == true) {
            if (dVal.equals("0")) {
                dVal = "4";
                l = PApplet.parseFloat(dVal);
            } else {
                dVal += "4";
                l = PApplet.parseFloat(dVal);
            }
        } else if (!left)
          if (dVal.equals("0")) {
            dVal = "4";
            r = PApplet.parseFloat(dVal);
          } else {
            dVal += "4";
            r = PApplet.parseFloat(dVal);
          }
      }
  }
  else if (keyCode == 53 || keyCode == 101) {
    if (dVal.length()<17) {
        if (left == true) {
            if (dVal.equals("0")) {
                dVal = "5";
                l = PApplet.parseFloat(dVal);
            } else {
                dVal += "5";
                l = PApplet.parseFloat(dVal);
            }
        } else if (!left)
          if (dVal.equals("0")) {
            dVal = "5";
            r = PApplet.parseFloat(dVal);
          } else {
            dVal += "5";
            r = PApplet.parseFloat(dVal);
          }
      }
  }
  else if (keyCode == 54 || keyCode == 102) {
    if (dVal.length()<17) {
        if (left == true) {
            if (dVal.equals("0")) {
                dVal = "6";
                l = PApplet.parseFloat(dVal);
            } else {
                dVal += "6";
                l = PApplet.parseFloat(dVal);
            }
        } else if (!left)
          if (dVal.equals("0")) {
            dVal = "6";
            r = PApplet.parseFloat(dVal);
          } else {
            dVal += "6";
            r = PApplet.parseFloat(dVal);
          }
      }
  }
  else if (keyCode == 55 || keyCode == 103) {
    if (dVal.length()<17) {
        if (left == true) {
            if (dVal.equals("0")) {
                dVal = "7";
                l = PApplet.parseFloat(dVal);
            } else {
                dVal += "7";
                l = PApplet.parseFloat(dVal);
            }
        } else if (!left)
          if (dVal.equals("0")) {
            dVal = "7";
            r = PApplet.parseFloat(dVal);
          } else {
            dVal += "7";
            r = PApplet.parseFloat(dVal);
          }
      }
  }
  else if (keyCode == 56 || keyCode == 104) {
    if (dVal.length()<17) {
        if (left == true) {
            if (dVal.equals("0")) {
                dVal = "8";
                l = PApplet.parseFloat(dVal);
            } else {
                dVal += "8";
                l = PApplet.parseFloat(dVal);
            }
        } else if (!left)
          if (dVal.equals("0")) {
            dVal = "8";
            r = PApplet.parseFloat(dVal);
          } else {
            dVal += "8";
            r = PApplet.parseFloat(dVal);
          }
      }
  }
    else if (keyCode == 57 || keyCode == 105) {
    if (dVal.length()<17) {
        if (left == true) {
            if (dVal.equals("0")) {
                dVal = "9";
                l = PApplet.parseFloat(dVal);
            } else {
                dVal += "9";
                l = PApplet.parseFloat(dVal);
            }
        } else if (!left)
          if (dVal.equals("0")) {
            dVal = "9";
            r = PApplet.parseFloat(dVal);
          } else {
            dVal += "9";
            r = PApplet.parseFloat(dVal);
          }
      }
  }
    if (left) l = PApplet.parseFloat(dVal);
    else r = PApplet.parseFloat(dVal);
  }

 public void mousePressed() {
  for (int i = 0; i < numButtons.length; i++) {
    if (numButtons[i].over) {
      if (dVal.equals("0")) dVal = numButtons[i].val;
      else dVal += numButtons[i].val;

      if (left) l = PApplet.parseFloat(dVal);
      else r = PApplet.parseFloat(dVal);
    }
  }
}

 public void mouseReleased() {
  for (int i = 0; i < buttons.length; i++) {
    if (buttons[i].over && buttons[i].val.equals("C")) {
      l = r = result = 0;
      dVal = "0";
      op = "";
      left = true;
    } 
    else if (buttons[i].over && buttons[i].val.equals("del")) {
      if (dVal.length() > 1) dVal = dVal.substring(0, dVal.length() - 1);
      else dVal = "0";
      if (left) l = PApplet.parseFloat(dVal);
      else r = PApplet.parseFloat(dVal);
    } 
    else if (buttons[i].over && buttons[i].val.equals("+")) {
      op = "+";
      left = false;
      dVal = "0";
    } 
    else if (buttons[i].over && buttons[i].val.equals("-")) {
      op = "-";
      left = false;
      dVal = "0";
    } 
    else if (buttons[i].over && buttons[i].val.equals("*")) {
      op = "*";
      left = false;
      dVal = "0";
    } 
    else if (buttons[i].over && buttons[i].val.equals("/")) {
      op = "/";
      left = false;
      dVal = "0";
    } 
    else if (buttons[i].over && buttons[i].val.equals("^")) {
      op = "^";
      left = false;
      dVal = "0";
    } 
    else if (buttons[i].over && buttons[i].val.equals("=")) {
      performCalculation();
      left = true;
      l = result;
    } 
    else if (buttons[i].over && buttons[i].val.equals("+/-")) {
      float temp = PApplet.parseFloat(dVal) * -1;
      dVal = str(temp);
      if (left) l = temp;
      else r = temp;
    } 
    else if (buttons[i].over && buttons[i].val.equals("rnd")) {
      float temp = round(PApplet.parseFloat(dVal));
      dVal = str(temp);
      if (left) l = temp;
      else r = temp;
    } 
    else if (buttons[i].over && buttons[i].val.equals("√")) {
      float temp = sqrt(PApplet.parseFloat(dVal));
      dVal = str(temp);
      if (left) l = temp;
      else r = temp;
    } 
    else if (buttons[i].over && buttons[i].val.equals("π")) {
      if (left) l = PI;
      else r = PI;
      dVal = str(PI);
    } 
    else if (buttons[i].over && buttons[i].val.equals(".")) {
      if (!dVal.contains(".")) dVal += ".";
    }
  }

  println("l: " + l);
  println("r: " + r);
  println("result: " + result);
  println("left: " + left);
  println("op: " + op);
}

 public void updateDisplay() {
  rectMode(CORNER);
  fill(255);
  rect(10, 10, 175, 30, 5);
  fill(0);
  textSize(20);
  textAlign(RIGHT, CENTER);
  text(dVal, width - 20, 25);
}

 public void performCalculation() {
  if (op.equals("+")) result = l + r;
  else if (op.equals("-")) result = l - r;
  else if (op.equals("*")) result = l * r;
  else if (op.equals("/")) result = (r != 0) ? l / r : 0;
  else if (op.equals("^")) result = pow(l, r);

  dVal = str(result);
  l = result;
  left = true;
}
class Button {
int x, y, w, h;
int c1, c2;
String val;
boolean over;

Button(int x, int y, int w, int h, String val, int c1, int c2) {
this.x = x;
this.y = y;
this.w = w;
this.h = h;
this.val = val;
this.c1 = c1;
this.c2 = c2;
over = false;
}

 public void display() {
rectMode(CENTER);
fill(over ? c2 : c1);
rect(x, y, w, h, 8);
fill(0);
textAlign(CENTER, CENTER);
textSize(13);
text(val, x, y);
}

 public void hover(int tempX, int tempY) {
over = (tempX > x - w/2 && tempX < x + w/2 && tempY > y - h/2 && tempY < y + h/2);
}
}


  public void settings() { size(200, 300); }

  static public void main(String[] passedArgs) {
    String[] appletArgs = new String[] { "Calculator2" };
    if (passedArgs != null) {
      PApplet.main(concat(appletArgs, passedArgs));
    } else {
      PApplet.main(appletArgs);
    }
  }
}
